<a href="https://colab.research.google.com/github/Shujaat123/ACP_LSE/blob/main/Ablation_Study_of_ACP_LSE_Notebook_kFoldCV_740.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **ACP-LSE: Anti-cancer peptides classification using deep latent-space encoding of Composition of k-Spaced Amino Acid Pairs**


This code provide python implementation of ACP-LSE algorithm.

# Loading Useful packages

In [ ]:
## Load useful packages
import sys, os, re, gc
from scipy.io import savemat
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, StratifiedKFold
import matplotlib.pyplot as plt
from keras import optimizers
# from keras.utils.np_utils import to_categorical
from keras.utils import to_categorical # for keras > 2.0
from collections import Counter
import matplotlib.pyplot as plt
from keras.models import Model
from keras.layers import Input, Dense, BatchNormalization, Dropout
from keras import optimizers
from keras import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score, matthews_corrcoef, balanced_accuracy_score, precision_recall_fscore_support
from sklearn.metrics import auc, average_precision_score, precision_recall_curve, roc_curve

from keras import backend as K
from keras.models import load_model
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from random import sample
from imblearn.over_sampling import SMOTE

# Feature-Extraction

The CKSAAP feature encoding calculates the frequency of amino acid pairs separated by any k residues. The CKSAAP encoding scheme reflects the amino acid pair information in small and large range with in the peptides depending upon the value of k(gap). The encoding scheme is utilized from iFeature web server, using the following download link: (https://github.com/Superzchen/iFeature).


In [ ]:
!pip install wget
import wget
dataset_path='https://raw.githubusercontent.com/haichengyi/ACP-DL/master/acp740.txt'
wget.download(dataset_path, 'acp740.txt')

!pip install mrmr_selection
from mrmr import mrmr_classif

In [ ]:
def Convert_Seq2CKSAAP(train_seq, gap=8):
  cksaapfea = []
  seq_label = []
  for sseq in train_seq:
    temp= CKSAAP([sseq], gap=8)
    cksaapfea.append(temp[1][1:])
    seq_label.append(sseq[0])

  x = np.array(cksaapfea)
  y = np.array(seq_label)
  y[y=='ACP']=1
  y[y=='non-ACP']=0
  y = to_categorical(y)
  print('num pos:', sum(y[:,0]==1), 'num neg:', sum(y[:,0]==0))
  return x,y

def minSequenceLength(fastas):
    minLen = 10000
    for i in fastas:
        if minLen > len(i[1]):
            minLen = len(i[1])
    return minLen

def CKSAAP(fastas, gap=5, **kw):
    if gap < 0:
        print('Error: the gap should be equal or greater than zero' + '\n\n')
        return 0

    if minSequenceLength(fastas) < gap+2:
        print('Error: all the sequence length should be larger than the (gap value) + 2 = ' + str(gap+2) + '\n' + 'Current sequence length ='  + str(minSequenceLength(fastas)) + '\n\n')
        return 0

    AA = 'ACDEFGHIKLMNPQRSTVWY'
    encodings = []
    aaPairs = []
    for aa1 in AA:
        for aa2 in AA:
            aaPairs.append(aa1 + aa2)
    header = ['#']
    for g in range(gap+1):
        for aa in aaPairs:
            header.append(aa + '.gap' + str(g))
    encodings.append(header)
    for i in fastas:
        name, sequence = i[0], i[1]
        code = [name]
        for g in range(gap+1):
            myDict = {}
            for pair in aaPairs:
                myDict[pair] = 0
            sum = 0
            for index1 in range(len(sequence)):
                index2 = index1 + g + 1
                if index1 < len(sequence) and index2 < len(sequence) and sequence[index1] in AA and sequence[index2] in AA:
                    myDict[sequence[index1] + sequence[index2]] = myDict[sequence[index1] + sequence[index2]] + 1
                    sum = sum + 1
            for pair in aaPairs:
                code.append(myDict[pair] / sum)
        encodings.append(code)
    return encodings

In [ ]:
def load_seq_data(data_path,label):
  dataset = pd.read_csv(data_path,names=None,index_col=0, header=None)
  seq = []
  sample_count = 0

  for row in dataset.iterrows():
    if(row[0]!='>'):
      sample_count = sample_count +1
      array = [label, row[0]]
      name, sequence = array[0].split()[0], re.sub('[^ARNDCQEGHILKMFPSTWYV-]', '-', ''.join(array[1:]).upper())
      seq.append([name, sequence])

  print('# of ' + label + ' samples',sample_count)
  return seq

In [ ]:
def prepare_feature_acp740():
    path = r"acp740.txt"
    new_list=[]
    seq_list=[]
    label = []
    lis = []
    interaction_pair = {}
    RNA_seq_dict = {}
    protein_seq_dict = {}
    protein_index = 0
    with open(path, 'r') as fp:
        for line in fp:
            if line[0] == '>':
                values = line[1:].strip().split('|')
                label_temp = values[1]
                proteinName = values[0]
                proteinName_1=proteinName.split("_")
                new_list.append(proteinName_1[0])
    #             print(new_list)

                if label_temp == '1':
                    label.append(1)
                else:
                    label.append(0)
            else:
                seq = line[:-1]
                seq_list.append(seq)
        for i, item in enumerate(new_list):
            lis.append([item, seq_list[i]])

    return lis

ALL_seq=prepare_feature_acp740()

In [ ]:
# ## Loading and pre-processing PVP prediction dataset
# pos_seq_path = 'https://raw.githubusercontent.com/Shujaat123/AntiOxiLSE/main/AodPred/anti.txt'
# neg_seq_path = 'https://raw.githubusercontent.com/Shujaat123/AntiOxiLSE/main/AodPred/nonanti.txt'
# pos_seq = load_seq_data(pos_seq_path)
# neg_seq = load_seq_data(neg_seq_path)
# ALL_seq = pos_seq + neg_seq

# pos_ind_seq_path = 'https://raw.githubusercontent.com/Shujaat123/AntiOxiLSE/main/AodPred/JTB_AHB_2019_DB/AntiOxi_Independent.csv'
# pos_train_seq_path = 'https://raw.githubusercontent.com/Shujaat123/AntiOxiLSE/main/AodPred/JTB_AHB_2019_DB/AntiOxi_Training.txt'
# neg_all_seq_path = 'https://raw.githubusercontent.com/Shujaat123/AntiOxiLSE/main/AodPred/JTB_AHB_2019_DB/nonAntiOxi.csv'

pos_all_seq_path = 'https://raw.githubusercontent.com/Shujaat123/ACP_LSE/main/dataset_acp_JTB_2014/1-s2.0-S0022519313004190-mmc1.txt'
neg_all_seq_path = 'https://raw.githubusercontent.com/Shujaat123/ACP_LSE/main/dataset_acp_JTB_2014/1-s2.0-S0022519313004190-mmc2.txt'

pos_all_seq = load_seq_data(pos_all_seq_path,'POS')
neg_all_seq = load_seq_data(neg_all_seq_path,'NEG')

ALL_seq = pos_all_seq + neg_all_seq

print(len(pos_all_seq), len(neg_all_seq), len(ALL_seq))

# of POS samples 138
# of NEG samples 206
138 206 344


In [ ]:
print(ALL_seq)
ALL_seq740=prepare_feature_acp740()
print(ALL_seq740)

[['POS', 'GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV'], ['POS', 'GLFDIIKKIAESI'], ['POS', 'GLLDIVKKVVGAFGSL'], ['POS', 'GLFDIVKKVVGALGSL'], ['POS', 'GLFDIVKKVVGTLAGL'], ['POS', 'GLFDIAKKVIGVIGSL'], ['POS', 'GLFDIVKKIAGHIAGSI'], ['POS', 'GLFDIVKKIAGHIVSSI'], ['POS', 'AACARFIDDFCDTLTPNIYRPRDNGQRCYAVNGHRCDFTVFNTNNGGNPIRASTPNCKTVLRTAANRCPTGGRGKINPNAPFLFAIDPNDGDCSTNF'], ['POS', 'HGVSGHGQHGVHG'], ['POS', 'FKCRRWQWRMKKLGAPSITCVRRAF'], ['POS', 'KWKLFKKIKFLHSAKKF'], ['POS', 'KSSAYSLQMGATAIKQVKKLFKKWGW'], ['POS', 'GIGTKILGGVKTALKGALKELASTYAN'], ['POS', 'GIGGKILSGLKTALKGAAKELASTYLH'], ['POS', 'GIGGVLLSAGKAALKGLAKVLAEKYAN'], ['POS', 'SIGAKILGGVKTFFKGALKELASTYLQ'], ['POS', 'FLPLLAGLAANFLPTIICKISYKC'], ['POS', 'FVQWFSKFLGRIL'], ['POS', 'KWKIFKKIEKVGRNIRNGIIKAGPAVAVLGEAKAL'], ['POS', 'GWLKKIGKKIERVGQHTRDATIQTIGVAQQAANVAATLK'], ['POS', 'KWKLFKKIEKVGQNIRDGIIKAGPAVAVVGQATQIAK'], ['POS', 'SQLGDLGSGAGQGGGGGGSIRAAGGAFGKLEAAREEEFFYKKQKEQLERLKNDQIHQAEFHHQQIKEHEEAIQRHKDFLNNLHK'], ['POS', 'GIGKFLHSAKKFGKAFVGEIMNS'], ['

## Loading and pre-processing protein's dataset

# Designing an Auto-Encoder-based classifier model

In [ ]:
## Designing an Auto-Encoder-Classifier model
def LSE_Final_Model(input_shape=3600, LV=5):
    # Encoder Network
    enc_input = Input(shape=(input_shape,), name='enc_input')
    enc_l1 = Dense(50, activation='relu', name='encoder_layer1')(enc_input)
    enc_l1 = BatchNormalization()(enc_l1)
    enc_l1 = Dropout(rate = 0.3)(enc_l1)

    enc_l2 = Dense(25, activation='relu', name='encoder_layer2')(enc_l1)
    enc_l2 = BatchNormalization()(enc_l2)
    enc_l2 = Dropout(rate = 0.3)(enc_l2)

    enc_l3 = Dense(10, activation='relu', name='encoder_layer3')(enc_l2)
    enc_l3 = BatchNormalization()(enc_l3)
    enc_l3 = Dropout(rate = 0.3)(enc_l3)

    encoder_output = Dense(LV, activation='sigmoid', name='encoder_output')(enc_l3)

    # Classifier Network
    class_l1 = Dense(10, activation='relu', name='class_layer1')(encoder_output)
    class_l2 = Dense(10, activation='relu', name='class_layer3')(class_l1)
    class_output = Dense(2, activation='softmax', name='class_output')(class_l2)

    # Decoder Network
    dec_l1 = Dense(10, activation='relu', name='decoder_layer1')(encoder_output)
    dec_l1 = BatchNormalization()(dec_l1)
    dec_l1 = Dropout(rate = 0.3)(dec_l1)

    dec_l2 = Dense(25, activation='relu', name='decoder_layer2')(dec_l1)
    dec_l2 = BatchNormalization()(dec_l2)
    dec_l2 = Dropout(rate = 0.3)(dec_l2)

    dec_l3 = Dense(50, activation='relu', name='decoder_layer3')(dec_l2)
    dec_l3 = BatchNormalization()(dec_l3)
    dec_l3 = Dropout(rate = 0.3)(dec_l3)

    decoder_output = Dense(input_shape, activation='sigmoid', name='decoder_output')(dec_l3)

    model = Model(inputs=[enc_input], outputs=[class_output, decoder_output])

    # Compiling model
    model.compile(optimizer='rmsprop',
                  loss={'class_output': 'binary_crossentropy', 'decoder_output': 'mean_squared_error'},
                  loss_weights={'class_output': 0.999, 'decoder_output': 0.001},
                  metrics=[metrics.categorical_accuracy])
    # Here I used rmsprops optimizer with default values, two objective functions are optimized
    # using  weight factors [1 for classifier and 0.1 for decoder loss]
    return model

## Define performance measures

In [ ]:
## Define performance measures
def yoden_index(y, y_pred):
  tn, fp, fn, tp = confusion_matrix(y, y_pred, labels=[0,1]).ravel()
  j = (tp/(tp+fn)) + (tn/(tn+fp)) - 1
  return j

def pmeasure(y, y_pred):
    tn, fp, fn, tp = confusion_matrix(y, y_pred, labels=[0,1]).ravel()
    sensitivity = tp / (tp + fn )
    specificity = tn / (tn + fp)
    f1score = (2 * tp) / (2 * tp + fp + fn)
    return ({'Sensitivity': sensitivity, 'Specificity': specificity, 'F1-Score': f1score})

def Show_Statistics(msg,Stats):
  print(msg.upper())
  print(70*'-')
  print('Accuracy:',Stats[0])
  print('Sensitivity:',Stats[1])
  print('Specificity:',Stats[2])
  print('F1-Score:',Stats[3])
  print('MCC:',Stats[4])
  print('Balance Accuracy:',Stats[5])
  print('Youden-Index:',Stats[6])
  print('AUC:',Stats[7])
  print('AUPR:',Stats[8])
  print('Reconstruction MSE:',Stats[9])
  print(70*'-')

def Calculate_Stats(y_actual,y_pred, y_score):
  acc = accuracy_score(y_actual.argmax(axis=1), y_pred.argmax(axis=1))
  sen = pmeasure(y_actual.argmax(axis=1), y_pred.argmax(axis=1))['Sensitivity']
  spe = pmeasure(y_actual.argmax(axis=1), y_pred.argmax(axis=1))['Specificity']
  f1 = pmeasure(y_actual.argmax(axis=1), y_pred.argmax(axis=1))['F1-Score']
  mcc = matthews_corrcoef(y_actual.argmax(axis=1), y_pred.argmax(axis=1))
  bacc = balanced_accuracy_score(y_actual.argmax(axis=1), y_pred.argmax(axis=1))
  yi = yoden_index(y_actual.argmax(axis=1), y_pred.argmax(axis=1))
  #auc = roc_auc_score(y_actual.argmax(axis=1), y_pred.argmax(axis=1))

  pre, rec, _ = precision_recall_curve(y_actual.argmax(axis=1), y_score, pos_label=1)
  fpr, tpr, _ = roc_curve(y_actual.argmax(axis=1), y_score, pos_label=1)
  auroc = auc(fpr, tpr)
  aupr = auc(rec, pre)

  return acc, sen, spe, f1, mcc, bacc, yi, auroc, aupr

def label_by_th(y_pred, threshold=0.5):
  y_pred_copy = y_pred.copy()
  y_pred_copy[y_pred>= threshold] = 1
  y_pred_copy[y_pred<threshold] = 0
  return y_pred_copy

def cutoff_youdens_j(fpr,tpr,thresholds):
  j_scores = tpr-fpr
  j_ordered = sorted(zip(j_scores,thresholds))
  return j_ordered[-1][1]

In [ ]:
from sklearn.preprocessing import Normalizer

  ## Perform Monte-Carlos Simulations for [num_Trials]\# of independent Trials


In [ ]:
## Perform Monte-Carlos Simulations for [num_Trials]# of independent Trials
LVs = range(3,4)
num_Trails = 1
gaps = range(4,5)
# kf = KFold(n_splits=5)
kf = StratifiedKFold(n_splits=5,shuffle=True, random_state=25)
# kf = StratifiedKFold(n_splits=10)
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

for gap_ind in range(0,len(gaps)):
    # [DataX, LabelY] = Convert_Seq2CKSAAP(ALL_seq, gap=gaps[gap_ind])
    [DataX, LabelY] = Convert_Seq2CKSAAP(prepare_feature_acp740(), gap=gaps[gap_ind])
    # DataX = preprocessing.normalize(DataX, norm='l2')

    # selected_features = mrmr_classif(X=pd.DataFrame(DataX), y=pd.Series(LabelY[:,0]), K=100)
    # DataX = DataX[:,selected_features]

    for lv_ind in range(0,len(LVs)):
      Stats =[]
      loop_ind = -1

      for train_index, test_index in kf.split(DataX,LabelY.argmax(axis=1)):
        loop_ind = loop_ind + 1
        X_train, X_test = DataX[train_index], DataX[test_index]
        y_train, y_test = LabelY[train_index], LabelY[test_index]

        transformer = Normalizer().fit(X_train)  # fit does nothing.
        X_train=transformer.transform(X_train)
        X_test=transformer.transform(X_test)
        # print(X_train.shape,y_train.shape)
        # print(X_test.shape,y_test.shape)
        # sm = SMOTE(random_state=(gaps[gap_ind]+LVs[lv_ind]+loop_ind+1))
        # X_train, y_train = sm.fit_resample(X_train, y_train)
        # y_train = to_categorical(y_train)

        # selected_features = mrmr_classif(X=pd.DataFrame(X_train), y=pd.Series(y_train[:,0]), K=700)
        # X_train = X_train[:,selected_features]
        # X_test = X_test[:,selected_features]

        model = LSE_Final_Model(input_shape = X_train.shape[1],LV=LVs[lv_ind])
        es = EarlyStopping(monitor='val_loss', mode='min', verbose=0, patience=50)
        checkpoint = ModelCheckpoint('models\\model-best.h5',
                                    verbose=0, monitor='val_loss',save_best_only=True, mode='auto')
        history = model.fit({'enc_input': X_train},
                          {'class_output': y_train, 'decoder_output': X_train},
                          validation_data = ({'enc_input': X_test},
                          {'class_output': y_test, 'decoder_output': X_test}),
                          epochs=1000, batch_size=y_train.shape[0], callbacks=[checkpoint, es], verbose=0)
        del model  # deletes the existing model
        model = load_model('models\\model-best.h5')

        y_train_pred, X_train_pred = model.predict(X_train,batch_size=1800, verbose=0)
        y_train_score = y_train_pred[:,1]
        y_train_pred = to_categorical(y_train_pred.argmax(axis=1))
        MSE_X_train_pred = (np.square(X_train_pred - X_train)).mean(axis=1)

        y_test_pred, X_test_pred = model.predict(X_test,batch_size=200, verbose=0)
        y_test_score = y_test_pred[:,1]

        # Optimal Threshold
        fpr, tpr, thresholds_AUC = roc_curve(y_test.argmax(axis=1), y_test_score)
        precision, recall, thresholds_AUPR = precision_recall_curve(y_test.argmax(axis=1),y_test_score)

        ## Optimal Threshold metrics
        distance = (1-fpr)**2+(1-tpr)**2
        EERs = (1-recall)/(1-precision)
        positive = sum(y_test.argmax(axis=1))
        negative = y_test.shape[0]-positive
        ratio = negative/positive
        opt_t_AUC = thresholds_AUC[np.argmin(distance)]
        opt_t_AUPR = thresholds_AUPR[np.argmin(np.abs(EERs-ratio))]
        opt_yodens_j = cutoff_youdens_j(fpr, tpr, thresholds_AUC)
        y_test_pred_th = label_by_th(y_test_score, opt_yodens_j)
        y_test_pred = to_categorical(y_test_pred_th)
        MSE_X_test_pred = (np.square(X_test_pred - X_test)).mean(axis=1)

        print(confusion_matrix(y_test.argmax(axis=1), y_test_pred.argmax(axis=1), labels=[0,1]).ravel())

        ## Training Measures
        tr_acc, tr_sen, tr_spe, tr_f1, tr_mcc, tr_bacc, tr_yi, tr_auc, tr_aupr = Calculate_Stats(y_train,y_train_pred, y_train_score);

        ## Test Measures
        t_acc, t_sen, t_spe, t_f1, t_mcc, t_bacc, t_yi, t_auc, t_aupr = Calculate_Stats(y_test,y_test_pred, y_test_score);

        Stats.append([tr_acc, tr_sen, tr_spe, tr_f1, tr_mcc, tr_bacc, tr_yi, tr_auc, tr_aupr, -10*np.log10(MSE_X_train_pred.mean()),
                      t_acc, t_sen, t_spe, t_f1, t_mcc, t_bacc, t_yi, t_auc, t_aupr,-10*np.log10(MSE_X_test_pred.mean())])
        print('CKSAAP-Gap:',gaps[gap_ind], 'LV=',LVs[lv_ind],'Trial:',loop_ind,
              ' \nTraining/ Test Youden-index:', tr_yi,'/',t_yi,
              ' \nTraining/ Test MCC:', tr_mcc,'/',t_mcc,
              ' \nTraining/ Test AUC:', tr_auc,'/',t_auc,
              ' \nTraining/ Test AUPR:', tr_aupr,'/',t_aupr,
              ' \nTraining/ Test MSE (dB):', -10*np.log10(MSE_X_train_pred.mean()), '/', -10*np.log10(MSE_X_test_pred.mean()))

      del model  # deletes the existing model
      Statistics = np.asarray(Stats)
      filename = 'ACP_LSE_STATS_CKSAAP_GAP' + str(gaps[gap_ind]) + '_LV' + str(LVs[lv_ind]) + '.mat'
      savemat(filename,{'Statistics':Statistics})
      print('SAVING... '+ filename)

num pos: 364 num neg: 376
[58 14 10 66]
CKSAAP-Gap: 4 LV= 3 Trial: 0  
Training/ Test Youden-index: 1.0 / 0.6739766081871346  
Training/ Test MCC: 1.0 / 0.6759559857476245  
Training/ Test AUC: 1.0 / 0.9040570175438596  
Training/ Test AUPR: 1.0 / 0.9137366480317995  
Training/ Test MSE (dB): 6.069095952761948 / 6.069868667552828
[64  9 10 65]
CKSAAP-Gap: 4 LV= 3 Trial: 1  
Training/ Test Youden-index: 1.0 / 0.7433789954337899  
Training/ Test MCC: 1.0 / 0.7433111162394346  
Training/ Test AUC: 1.0 / 0.9073972602739727  
Training/ Test AUPR: 1.0 / 0.8989769986780903  
Training/ Test MSE (dB): 6.064753376306964 / 6.064435149488547
[56 17  7 68]
CKSAAP-Gap: 4 LV= 3 Trial: 2  
Training/ Test Youden-index: 1.0 / 0.6737899543378996  
Training/ Test MCC: 1.0 / 0.6812975950260876  
Training/ Test AUC: 1.0 / 0.89662100456621  
Training/ Test AUPR: 1.0 / 0.9058536098313382  
Training/ Test MSE (dB): 6.066523517445971 / 6.0688154788731214
[65  8 23 52]
CKSAAP-Gap: 4 LV= 3 Trial: 3  
Training/ Te

## Show Classification/Reconstruction Statistics

In [ ]:
## Show Classification/Reconstruction Statistics
Show_Statistics('Training Results (MEAN)',Statistics.mean(axis=0)[0:10])
Show_Statistics('Test Results (MEAN)',Statistics.mean(axis=0)[10:20])

TRAINING RESULTS (MEAN)
----------------------------------------------------------------------
Accuracy: 0.9016891891891892
Sensitivity: 1.0
Specificity: 0.8
F1-Score: 0.9348264277715564
MCC: 0.8
Balance Accuracy: 0.9
Youden-Index: 0.8
AUC: 0.9981801783288237
AUPR: 0.9987928942769345
Reconstruction MSE: 6.069864312682682
----------------------------------------------------------------------
TEST RESULTS (MEAN)
----------------------------------------------------------------------
Accuracy: 0.835135135135135
Sensitivity: 0.8323508771929824
Specificity: 0.8378234398782345
F1-Score: 0.8353690551677129
MCC: 0.6741944728984112
Balance Accuracy: 0.8350871585356086
Youden-Index: 0.6701743170712169
AUC: 0.8890123167507811
AUPR: 0.8911010333113529
Reconstruction MSE: 6.069961893677877
----------------------------------------------------------------------
